services:
  - type: web
    name: farmdreamerp
    env: node
    plan: free
    buildCommand: npm ci && npm run build:client
    startCommand: NODE_ENV=production npx tsx server/index.ts
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 3000
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate